api_users:
    resource: ../src/User/Http/
    type: annotation
    prefix: /api
    defaults:
        _format: json

api_posts:
    resource: ../src/Post/Http/
    type: annotation
    prefix: /api
    defaults:
        _format: json

api_upload:
    resource: ../src/Upload
    type: annotation
    prefix: /api
    defaults:
        _format: json

api_login:
    path: /api/login