# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Users\:
        resource: '../src/Users/*'
        exclude: '../src/Users/{Entity}'

    App\Common\Doctrine\MigrationEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: 'default' }

    App\Common\EventListener\JsonRequestTransformerListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }

    AppBundle\Listener\DomainExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onDomainException }
