# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

imports:
    - { resource: ./../src/Core/Resources/config/services.yaml }
    - { resource: ./../src/Security/Resources/config/services.yaml }
    - { resource: ./../src/Upload/Resources/config/services.yaml }
    - { resource: ./../src/User/Resources/config/services.yaml }
    - { resource: ./../src/Post/Resources/config/services.yaml }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactoryInterface: '@serializer.mapping.class_metadata_factory'
    Symfony\Component\Serializer\NameConverter\NameConverterInterface: '@serializer.name_converter.camel_case_to_snake_case'
    Symfony\Component\PropertyInfo\PropertyTypeExtractorInterface: '@property_info.reflection_extractor'

    Symfony\Component\Serializer\Normalizer\PropertyNormalizer:
        tags: [ serializer.normalizer ]